//------------------------------------------------------------------------------
// <auto-generated>
//     This code has been generated by T4 Text Template.
//     Generated date : 08/28/2015 17:00:01
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;

namespace Afk.ZoneInfo {

	/// <summary>
	/// Enumerate all time zone
	/// </summary>
	public sealed class Zones {
		/// <summary>
		/// Initiliaze a new instance of <see cref="Zones"/>
		/// </summary>
		private Zones() { }

		/// <summary>
		/// Represents all timezones for Africa
		/// </summary>
		public sealed class Africa {
			/// <summary>
			/// Initiliaze a new instance of <see cref="Africa"/>
			/// </summary>
			private Africa() { }

			/// <summary>
			/// Get the timezone for Africa/Abidjan
			/// </summary>
			public static TzTimeZone Abidjan { get { return TzTimeInfo.GetZone("Africa/Abidjan"); } }
			/// <summary>
			/// Get the timezone for Africa/Accra
			/// </summary>
			public static TzTimeZone Accra { get { return TzTimeInfo.GetZone("Africa/Accra"); } }
			/// <summary>
			/// Get the timezone for Africa/Algiers
			/// </summary>
			public static TzTimeZone Algiers { get { return TzTimeInfo.GetZone("Africa/Algiers"); } }
			/// <summary>
			/// Get the timezone for Africa/Bissau
			/// </summary>
			public static TzTimeZone Bissau { get { return TzTimeInfo.GetZone("Africa/Bissau"); } }
			/// <summary>
			/// Get the timezone for Africa/Cairo
			/// </summary>
			public static TzTimeZone Cairo { get { return TzTimeInfo.GetZone("Africa/Cairo"); } }
			/// <summary>
			/// Get the timezone for Africa/Casablanca
			/// </summary>
			public static TzTimeZone Casablanca { get { return TzTimeInfo.GetZone("Africa/Casablanca"); } }
			/// <summary>
			/// Get the timezone for Africa/Ceuta
			/// </summary>
			public static TzTimeZone Ceuta { get { return TzTimeInfo.GetZone("Africa/Ceuta"); } }
			/// <summary>
			/// Get the timezone for Africa/El_Aaiun
			/// </summary>
			public static TzTimeZone El_Aaiun { get { return TzTimeInfo.GetZone("Africa/El_Aaiun"); } }
			/// <summary>
			/// Get the timezone for Africa/Johannesburg
			/// </summary>
			public static TzTimeZone Johannesburg { get { return TzTimeInfo.GetZone("Africa/Johannesburg"); } }
			/// <summary>
			/// Get the timezone for Africa/Khartoum
			/// </summary>
			public static TzTimeZone Khartoum { get { return TzTimeInfo.GetZone("Africa/Khartoum"); } }
			/// <summary>
			/// Get the timezone for Africa/Lagos
			/// </summary>
			public static TzTimeZone Lagos { get { return TzTimeInfo.GetZone("Africa/Lagos"); } }
			/// <summary>
			/// Get the timezone for Africa/Maputo
			/// </summary>
			public static TzTimeZone Maputo { get { return TzTimeInfo.GetZone("Africa/Maputo"); } }
			/// <summary>
			/// Get the timezone for Africa/Monrovia
			/// </summary>
			public static TzTimeZone Monrovia { get { return TzTimeInfo.GetZone("Africa/Monrovia"); } }
			/// <summary>
			/// Get the timezone for Africa/Nairobi
			/// </summary>
			public static TzTimeZone Nairobi { get { return TzTimeInfo.GetZone("Africa/Nairobi"); } }
			/// <summary>
			/// Get the timezone for Africa/Ndjamena
			/// </summary>
			public static TzTimeZone Ndjamena { get { return TzTimeInfo.GetZone("Africa/Ndjamena"); } }
			/// <summary>
			/// Get the timezone for Africa/Tripoli
			/// </summary>
			public static TzTimeZone Tripoli { get { return TzTimeInfo.GetZone("Africa/Tripoli"); } }
			/// <summary>
			/// Get the timezone for Africa/Tunis
			/// </summary>
			public static TzTimeZone Tunis { get { return TzTimeInfo.GetZone("Africa/Tunis"); } }
			/// <summary>
			/// Get the timezone for Africa/Windhoek
			/// </summary>
			public static TzTimeZone Windhoek { get { return TzTimeInfo.GetZone("Africa/Windhoek"); } }
		}
		/// <summary>
		/// Represents all timezones for America
		/// </summary>
		public sealed class America {
			/// <summary>
			/// Initiliaze a new instance of <see cref="America"/>
			/// </summary>
			private America() { }

			/// <summary>
			/// Get the timezone for America/Adak
			/// </summary>
			public static TzTimeZone Adak { get { return TzTimeInfo.GetZone("America/Adak"); } }
			/// <summary>
			/// Get the timezone for America/Anchorage
			/// </summary>
			public static TzTimeZone Anchorage { get { return TzTimeInfo.GetZone("America/Anchorage"); } }
			/// <summary>
			/// Get the timezone for America/Araguaina
			/// </summary>
			public static TzTimeZone Araguaina { get { return TzTimeInfo.GetZone("America/Araguaina"); } }
			/// <summary>
			/// Represents all timezones for Argentina
			/// </summary>
			public sealed class Argentina {
				/// <summary>
				/// Initiliaze a new instance of <see cref="Argentina"/>
				/// </summary>
				private Argentina() { }

				/// <summary>
				/// Get the timezone for America/Argentina/Buenos_Aires
				/// </summary>
				public static TzTimeZone Buenos_Aires { get { return TzTimeInfo.GetZone("America/Argentina/Buenos_Aires"); } }
				/// <summary>
				/// Get the timezone for America/Argentina/Catamarca
				/// </summary>
				public static TzTimeZone Catamarca { get { return TzTimeInfo.GetZone("America/Argentina/Catamarca"); } }
				/// <summary>
				/// Get the timezone for America/Argentina/Cordoba
				/// </summary>
				public static TzTimeZone Cordoba { get { return TzTimeInfo.GetZone("America/Argentina/Cordoba"); } }
				/// <summary>
				/// Get the timezone for America/Argentina/Jujuy
				/// </summary>
				public static TzTimeZone Jujuy { get { return TzTimeInfo.GetZone("America/Argentina/Jujuy"); } }
				/// <summary>
				/// Get the timezone for America/Argentina/La_Rioja
				/// </summary>
				public static TzTimeZone La_Rioja { get { return TzTimeInfo.GetZone("America/Argentina/La_Rioja"); } }
				/// <summary>
				/// Get the timezone for America/Argentina/Mendoza
				/// </summary>
				public static TzTimeZone Mendoza { get { return TzTimeInfo.GetZone("America/Argentina/Mendoza"); } }
				/// <summary>
				/// Get the timezone for America/Argentina/Rio_Gallegos
				/// </summary>
				public static TzTimeZone Rio_Gallegos { get { return TzTimeInfo.GetZone("America/Argentina/Rio_Gallegos"); } }
				/// <summary>
				/// Get the timezone for America/Argentina/Salta
				/// </summary>
				public static TzTimeZone Salta { get { return TzTimeInfo.GetZone("America/Argentina/Salta"); } }
				/// <summary>
				/// Get the timezone for America/Argentina/San_Juan
				/// </summary>
				public static TzTimeZone San_Juan { get { return TzTimeInfo.GetZone("America/Argentina/San_Juan"); } }
				/// <summary>
				/// Get the timezone for America/Argentina/San_Luis
				/// </summary>
				public static TzTimeZone San_Luis { get { return TzTimeInfo.GetZone("America/Argentina/San_Luis"); } }
				/// <summary>
				/// Get the timezone for America/Argentina/Tucuman
				/// </summary>
				public static TzTimeZone Tucuman { get { return TzTimeInfo.GetZone("America/Argentina/Tucuman"); } }
				/// <summary>
				/// Get the timezone for America/Argentina/Ushuaia
				/// </summary>
				public static TzTimeZone Ushuaia { get { return TzTimeInfo.GetZone("America/Argentina/Ushuaia"); } }
			}
			/// <summary>
			/// Get the timezone for America/Asuncion
			/// </summary>
			public static TzTimeZone Asuncion { get { return TzTimeInfo.GetZone("America/Asuncion"); } }
			/// <summary>
			/// Get the timezone for America/Atikokan
			/// </summary>
			public static TzTimeZone Atikokan { get { return TzTimeInfo.GetZone("America/Atikokan"); } }
			/// <summary>
			/// Get the timezone for America/Bahia
			/// </summary>
			public static TzTimeZone Bahia { get { return TzTimeInfo.GetZone("America/Bahia"); } }
			/// <summary>
			/// Get the timezone for America/Bahia_Banderas
			/// </summary>
			public static TzTimeZone Bahia_Banderas { get { return TzTimeInfo.GetZone("America/Bahia_Banderas"); } }
			/// <summary>
			/// Get the timezone for America/Barbados
			/// </summary>
			public static TzTimeZone Barbados { get { return TzTimeInfo.GetZone("America/Barbados"); } }
			/// <summary>
			/// Get the timezone for America/Belem
			/// </summary>
			public static TzTimeZone Belem { get { return TzTimeInfo.GetZone("America/Belem"); } }
			/// <summary>
			/// Get the timezone for America/Belize
			/// </summary>
			public static TzTimeZone Belize { get { return TzTimeInfo.GetZone("America/Belize"); } }
			/// <summary>
			/// Get the timezone for America/Blanc-Sablon
			/// </summary>
			public static TzTimeZone Blanc_Sablon { get { return TzTimeInfo.GetZone("America/Blanc-Sablon"); } }
			/// <summary>
			/// Get the timezone for America/Boa_Vista
			/// </summary>
			public static TzTimeZone Boa_Vista { get { return TzTimeInfo.GetZone("America/Boa_Vista"); } }
			/// <summary>
			/// Get the timezone for America/Bogota
			/// </summary>
			public static TzTimeZone Bogota { get { return TzTimeInfo.GetZone("America/Bogota"); } }
			/// <summary>
			/// Get the timezone for America/Boise
			/// </summary>
			public static TzTimeZone Boise { get { return TzTimeInfo.GetZone("America/Boise"); } }
			/// <summary>
			/// Get the timezone for America/Cambridge_Bay
			/// </summary>
			public static TzTimeZone Cambridge_Bay { get { return TzTimeInfo.GetZone("America/Cambridge_Bay"); } }
			/// <summary>
			/// Get the timezone for America/Campo_Grande
			/// </summary>
			public static TzTimeZone Campo_Grande { get { return TzTimeInfo.GetZone("America/Campo_Grande"); } }
			/// <summary>
			/// Get the timezone for America/Cancun
			/// </summary>
			public static TzTimeZone Cancun { get { return TzTimeInfo.GetZone("America/Cancun"); } }
			/// <summary>
			/// Get the timezone for America/Caracas
			/// </summary>
			public static TzTimeZone Caracas { get { return TzTimeInfo.GetZone("America/Caracas"); } }
			/// <summary>
			/// Get the timezone for America/Cayenne
			/// </summary>
			public static TzTimeZone Cayenne { get { return TzTimeInfo.GetZone("America/Cayenne"); } }
			/// <summary>
			/// Get the timezone for America/Cayman
			/// </summary>
			public static TzTimeZone Cayman { get { return TzTimeInfo.GetZone("America/Cayman"); } }
			/// <summary>
			/// Get the timezone for America/Chicago
			/// </summary>
			public static TzTimeZone Chicago { get { return TzTimeInfo.GetZone("America/Chicago"); } }
			/// <summary>
			/// Get the timezone for America/Chihuahua
			/// </summary>
			public static TzTimeZone Chihuahua { get { return TzTimeInfo.GetZone("America/Chihuahua"); } }
			/// <summary>
			/// Get the timezone for America/Costa_Rica
			/// </summary>
			public static TzTimeZone Costa_Rica { get { return TzTimeInfo.GetZone("America/Costa_Rica"); } }
			/// <summary>
			/// Get the timezone for America/Creston
			/// </summary>
			public static TzTimeZone Creston { get { return TzTimeInfo.GetZone("America/Creston"); } }
			/// <summary>
			/// Get the timezone for America/Cuiaba
			/// </summary>
			public static TzTimeZone Cuiaba { get { return TzTimeInfo.GetZone("America/Cuiaba"); } }
			/// <summary>
			/// Get the timezone for America/Curacao
			/// </summary>
			public static TzTimeZone Curacao { get { return TzTimeInfo.GetZone("America/Curacao"); } }
			/// <summary>
			/// Get the timezone for America/Danmarkshavn
			/// </summary>
			public static TzTimeZone Danmarkshavn { get { return TzTimeInfo.GetZone("America/Danmarkshavn"); } }
			/// <summary>
			/// Get the timezone for America/Dawson
			/// </summary>
			public static TzTimeZone Dawson { get { return TzTimeInfo.GetZone("America/Dawson"); } }
			/// <summary>
			/// Get the timezone for America/Dawson_Creek
			/// </summary>
			public static TzTimeZone Dawson_Creek { get { return TzTimeInfo.GetZone("America/Dawson_Creek"); } }
			/// <summary>
			/// Get the timezone for America/Denver
			/// </summary>
			public static TzTimeZone Denver { get { return TzTimeInfo.GetZone("America/Denver"); } }
			/// <summary>
			/// Get the timezone for America/Detroit
			/// </summary>
			public static TzTimeZone Detroit { get { return TzTimeInfo.GetZone("America/Detroit"); } }
			/// <summary>
			/// Get the timezone for America/Edmonton
			/// </summary>
			public static TzTimeZone Edmonton { get { return TzTimeInfo.GetZone("America/Edmonton"); } }
			/// <summary>
			/// Get the timezone for America/Eirunepe
			/// </summary>
			public static TzTimeZone Eirunepe { get { return TzTimeInfo.GetZone("America/Eirunepe"); } }
			/// <summary>
			/// Get the timezone for America/El_Salvador
			/// </summary>
			public static TzTimeZone El_Salvador { get { return TzTimeInfo.GetZone("America/El_Salvador"); } }
			/// <summary>
			/// Get the timezone for America/Fortaleza
			/// </summary>
			public static TzTimeZone Fortaleza { get { return TzTimeInfo.GetZone("America/Fortaleza"); } }
			/// <summary>
			/// Get the timezone for America/Glace_Bay
			/// </summary>
			public static TzTimeZone Glace_Bay { get { return TzTimeInfo.GetZone("America/Glace_Bay"); } }
			/// <summary>
			/// Get the timezone for America/Godthab
			/// </summary>
			public static TzTimeZone Godthab { get { return TzTimeInfo.GetZone("America/Godthab"); } }
			/// <summary>
			/// Get the timezone for America/Goose_Bay
			/// </summary>
			public static TzTimeZone Goose_Bay { get { return TzTimeInfo.GetZone("America/Goose_Bay"); } }
			/// <summary>
			/// Get the timezone for America/Grand_Turk
			/// </summary>
			public static TzTimeZone Grand_Turk { get { return TzTimeInfo.GetZone("America/Grand_Turk"); } }
			/// <summary>
			/// Get the timezone for America/Guatemala
			/// </summary>
			public static TzTimeZone Guatemala { get { return TzTimeInfo.GetZone("America/Guatemala"); } }
			/// <summary>
			/// Get the timezone for America/Guayaquil
			/// </summary>
			public static TzTimeZone Guayaquil { get { return TzTimeInfo.GetZone("America/Guayaquil"); } }
			/// <summary>
			/// Get the timezone for America/Guyana
			/// </summary>
			public static TzTimeZone Guyana { get { return TzTimeInfo.GetZone("America/Guyana"); } }
			/// <summary>
			/// Get the timezone for America/Halifax
			/// </summary>
			public static TzTimeZone Halifax { get { return TzTimeInfo.GetZone("America/Halifax"); } }
			/// <summary>
			/// Get the timezone for America/Havana
			/// </summary>
			public static TzTimeZone Havana { get { return TzTimeInfo.GetZone("America/Havana"); } }
			/// <summary>
			/// Get the timezone for America/Hermosillo
			/// </summary>
			public static TzTimeZone Hermosillo { get { return TzTimeInfo.GetZone("America/Hermosillo"); } }
			/// <summary>
			/// Represents all timezones for Indiana
			/// </summary>
			public sealed class Indiana {
				/// <summary>
				/// Initiliaze a new instance of <see cref="Indiana"/>
				/// </summary>
				private Indiana() { }

				/// <summary>
				/// Get the timezone for America/Indiana/Indianapolis
				/// </summary>
				public static TzTimeZone Indianapolis { get { return TzTimeInfo.GetZone("America/Indiana/Indianapolis"); } }
				/// <summary>
				/// Get the timezone for America/Indiana/Knox
				/// </summary>
				public static TzTimeZone Knox { get { return TzTimeInfo.GetZone("America/Indiana/Knox"); } }
				/// <summary>
				/// Get the timezone for America/Indiana/Marengo
				/// </summary>
				public static TzTimeZone Marengo { get { return TzTimeInfo.GetZone("America/Indiana/Marengo"); } }
				/// <summary>
				/// Get the timezone for America/Indiana/Petersburg
				/// </summary>
				public static TzTimeZone Petersburg { get { return TzTimeInfo.GetZone("America/Indiana/Petersburg"); } }
				/// <summary>
				/// Get the timezone for America/Indiana/Tell_City
				/// </summary>
				public static TzTimeZone Tell_City { get { return TzTimeInfo.GetZone("America/Indiana/Tell_City"); } }
				/// <summary>
				/// Get the timezone for America/Indiana/Vevay
				/// </summary>
				public static TzTimeZone Vevay { get { return TzTimeInfo.GetZone("America/Indiana/Vevay"); } }
				/// <summary>
				/// Get the timezone for America/Indiana/Vincennes
				/// </summary>
				public static TzTimeZone Vincennes { get { return TzTimeInfo.GetZone("America/Indiana/Vincennes"); } }
				/// <summary>
				/// Get the timezone for America/Indiana/Winamac
				/// </summary>
				public static TzTimeZone Winamac { get { return TzTimeInfo.GetZone("America/Indiana/Winamac"); } }
			}
			/// <summary>
			/// Get the timezone for America/Inuvik
			/// </summary>
			public static TzTimeZone Inuvik { get { return TzTimeInfo.GetZone("America/Inuvik"); } }
			/// <summary>
			/// Get the timezone for America/Iqaluit
			/// </summary>
			public static TzTimeZone Iqaluit { get { return TzTimeInfo.GetZone("America/Iqaluit"); } }
			/// <summary>
			/// Get the timezone for America/Jamaica
			/// </summary>
			public static TzTimeZone Jamaica { get { return TzTimeInfo.GetZone("America/Jamaica"); } }
			/// <summary>
			/// Get the timezone for America/Juneau
			/// </summary>
			public static TzTimeZone Juneau { get { return TzTimeInfo.GetZone("America/Juneau"); } }
			/// <summary>
			/// Represents all timezones for Kentucky
			/// </summary>
			public sealed class Kentucky {
				/// <summary>
				/// Initiliaze a new instance of <see cref="Kentucky"/>
				/// </summary>
				private Kentucky() { }

				/// <summary>
				/// Get the timezone for America/Kentucky/Louisville
				/// </summary>
				public static TzTimeZone Louisville { get { return TzTimeInfo.GetZone("America/Kentucky/Louisville"); } }
				/// <summary>
				/// Get the timezone for America/Kentucky/Monticello
				/// </summary>
				public static TzTimeZone Monticello { get { return TzTimeInfo.GetZone("America/Kentucky/Monticello"); } }
			}
			/// <summary>
			/// Get the timezone for America/La_Paz
			/// </summary>
			public static TzTimeZone La_Paz { get { return TzTimeInfo.GetZone("America/La_Paz"); } }
			/// <summary>
			/// Get the timezone for America/Lima
			/// </summary>
			public static TzTimeZone Lima { get { return TzTimeInfo.GetZone("America/Lima"); } }
			/// <summary>
			/// Get the timezone for America/Los_Angeles
			/// </summary>
			public static TzTimeZone Los_Angeles { get { return TzTimeInfo.GetZone("America/Los_Angeles"); } }
			/// <summary>
			/// Get the timezone for America/Maceio
			/// </summary>
			public static TzTimeZone Maceio { get { return TzTimeInfo.GetZone("America/Maceio"); } }
			/// <summary>
			/// Get the timezone for America/Managua
			/// </summary>
			public static TzTimeZone Managua { get { return TzTimeInfo.GetZone("America/Managua"); } }
			/// <summary>
			/// Get the timezone for America/Manaus
			/// </summary>
			public static TzTimeZone Manaus { get { return TzTimeInfo.GetZone("America/Manaus"); } }
			/// <summary>
			/// Get the timezone for America/Martinique
			/// </summary>
			public static TzTimeZone Martinique { get { return TzTimeInfo.GetZone("America/Martinique"); } }
			/// <summary>
			/// Get the timezone for America/Matamoros
			/// </summary>
			public static TzTimeZone Matamoros { get { return TzTimeInfo.GetZone("America/Matamoros"); } }
			/// <summary>
			/// Get the timezone for America/Mazatlan
			/// </summary>
			public static TzTimeZone Mazatlan { get { return TzTimeInfo.GetZone("America/Mazatlan"); } }
			/// <summary>
			/// Get the timezone for America/Menominee
			/// </summary>
			public static TzTimeZone Menominee { get { return TzTimeInfo.GetZone("America/Menominee"); } }
			/// <summary>
			/// Get the timezone for America/Merida
			/// </summary>
			public static TzTimeZone Merida { get { return TzTimeInfo.GetZone("America/Merida"); } }
			/// <summary>
			/// Get the timezone for America/Metlakatla
			/// </summary>
			public static TzTimeZone Metlakatla { get { return TzTimeInfo.GetZone("America/Metlakatla"); } }
			/// <summary>
			/// Get the timezone for America/Mexico_City
			/// </summary>
			public static TzTimeZone Mexico_City { get { return TzTimeInfo.GetZone("America/Mexico_City"); } }
			/// <summary>
			/// Get the timezone for America/Miquelon
			/// </summary>
			public static TzTimeZone Miquelon { get { return TzTimeInfo.GetZone("America/Miquelon"); } }
			/// <summary>
			/// Get the timezone for America/Moncton
			/// </summary>
			public static TzTimeZone Moncton { get { return TzTimeInfo.GetZone("America/Moncton"); } }
			/// <summary>
			/// Get the timezone for America/Monterrey
			/// </summary>
			public static TzTimeZone Monterrey { get { return TzTimeInfo.GetZone("America/Monterrey"); } }
			/// <summary>
			/// Get the timezone for America/Montevideo
			/// </summary>
			public static TzTimeZone Montevideo { get { return TzTimeInfo.GetZone("America/Montevideo"); } }
			/// <summary>
			/// Get the timezone for America/Nassau
			/// </summary>
			public static TzTimeZone Nassau { get { return TzTimeInfo.GetZone("America/Nassau"); } }
			/// <summary>
			/// Get the timezone for America/New_York
			/// </summary>
			public static TzTimeZone New_York { get { return TzTimeInfo.GetZone("America/New_York"); } }
			/// <summary>
			/// Get the timezone for America/Nipigon
			/// </summary>
			public static TzTimeZone Nipigon { get { return TzTimeInfo.GetZone("America/Nipigon"); } }
			/// <summary>
			/// Get the timezone for America/Nome
			/// </summary>
			public static TzTimeZone Nome { get { return TzTimeInfo.GetZone("America/Nome"); } }
			/// <summary>
			/// Get the timezone for America/Noronha
			/// </summary>
			public static TzTimeZone Noronha { get { return TzTimeInfo.GetZone("America/Noronha"); } }
			/// <summary>
			/// Represents all timezones for North_Dakota
			/// </summary>
			public sealed class North_Dakota {
				/// <summary>
				/// Initiliaze a new instance of <see cref="North_Dakota"/>
				/// </summary>
				private North_Dakota() { }

				/// <summary>
				/// Get the timezone for America/North_Dakota/Beulah
				/// </summary>
				public static TzTimeZone Beulah { get { return TzTimeInfo.GetZone("America/North_Dakota/Beulah"); } }
				/// <summary>
				/// Get the timezone for America/North_Dakota/Center
				/// </summary>
				public static TzTimeZone Center { get { return TzTimeInfo.GetZone("America/North_Dakota/Center"); } }
				/// <summary>
				/// Get the timezone for America/North_Dakota/New_Salem
				/// </summary>
				public static TzTimeZone New_Salem { get { return TzTimeInfo.GetZone("America/North_Dakota/New_Salem"); } }
			}
			/// <summary>
			/// Get the timezone for America/Ojinaga
			/// </summary>
			public static TzTimeZone Ojinaga { get { return TzTimeInfo.GetZone("America/Ojinaga"); } }
			/// <summary>
			/// Get the timezone for America/Panama
			/// </summary>
			public static TzTimeZone Panama { get { return TzTimeInfo.GetZone("America/Panama"); } }
			/// <summary>
			/// Get the timezone for America/Pangnirtung
			/// </summary>
			public static TzTimeZone Pangnirtung { get { return TzTimeInfo.GetZone("America/Pangnirtung"); } }
			/// <summary>
			/// Get the timezone for America/Paramaribo
			/// </summary>
			public static TzTimeZone Paramaribo { get { return TzTimeInfo.GetZone("America/Paramaribo"); } }
			/// <summary>
			/// Get the timezone for America/Phoenix
			/// </summary>
			public static TzTimeZone Phoenix { get { return TzTimeInfo.GetZone("America/Phoenix"); } }
			/// <summary>
			/// Get the timezone for America/Port_of_Spain
			/// </summary>
			public static TzTimeZone Port_of_Spain { get { return TzTimeInfo.GetZone("America/Port_of_Spain"); } }
			/// <summary>
			/// Get the timezone for America/Port-au-Prince
			/// </summary>
			public static TzTimeZone Port_au_Prince { get { return TzTimeInfo.GetZone("America/Port-au-Prince"); } }
			/// <summary>
			/// Get the timezone for America/Porto_Velho
			/// </summary>
			public static TzTimeZone Porto_Velho { get { return TzTimeInfo.GetZone("America/Porto_Velho"); } }
			/// <summary>
			/// Get the timezone for America/Puerto_Rico
			/// </summary>
			public static TzTimeZone Puerto_Rico { get { return TzTimeInfo.GetZone("America/Puerto_Rico"); } }
			/// <summary>
			/// Get the timezone for America/Rainy_River
			/// </summary>
			public static TzTimeZone Rainy_River { get { return TzTimeInfo.GetZone("America/Rainy_River"); } }
			/// <summary>
			/// Get the timezone for America/Rankin_Inlet
			/// </summary>
			public static TzTimeZone Rankin_Inlet { get { return TzTimeInfo.GetZone("America/Rankin_Inlet"); } }
			/// <summary>
			/// Get the timezone for America/Recife
			/// </summary>
			public static TzTimeZone Recife { get { return TzTimeInfo.GetZone("America/Recife"); } }
			/// <summary>
			/// Get the timezone for America/Regina
			/// </summary>
			public static TzTimeZone Regina { get { return TzTimeInfo.GetZone("America/Regina"); } }
			/// <summary>
			/// Get the timezone for America/Resolute
			/// </summary>
			public static TzTimeZone Resolute { get { return TzTimeInfo.GetZone("America/Resolute"); } }
			/// <summary>
			/// Get the timezone for America/Rio_Branco
			/// </summary>
			public static TzTimeZone Rio_Branco { get { return TzTimeInfo.GetZone("America/Rio_Branco"); } }
			/// <summary>
			/// Get the timezone for America/Santa_Isabel
			/// </summary>
			public static TzTimeZone Santa_Isabel { get { return TzTimeInfo.GetZone("America/Santa_Isabel"); } }
			/// <summary>
			/// Get the timezone for America/Santarem
			/// </summary>
			public static TzTimeZone Santarem { get { return TzTimeInfo.GetZone("America/Santarem"); } }
			/// <summary>
			/// Get the timezone for America/Santiago
			/// </summary>
			public static TzTimeZone Santiago { get { return TzTimeInfo.GetZone("America/Santiago"); } }
			/// <summary>
			/// Get the timezone for America/Santo_Domingo
			/// </summary>
			public static TzTimeZone Santo_Domingo { get { return TzTimeInfo.GetZone("America/Santo_Domingo"); } }
			/// <summary>
			/// Get the timezone for America/Sao_Paulo
			/// </summary>
			public static TzTimeZone Sao_Paulo { get { return TzTimeInfo.GetZone("America/Sao_Paulo"); } }
			/// <summary>
			/// Get the timezone for America/Scoresbysund
			/// </summary>
			public static TzTimeZone Scoresbysund { get { return TzTimeInfo.GetZone("America/Scoresbysund"); } }
			/// <summary>
			/// Get the timezone for America/Sitka
			/// </summary>
			public static TzTimeZone Sitka { get { return TzTimeInfo.GetZone("America/Sitka"); } }
			/// <summary>
			/// Get the timezone for America/St_Johns
			/// </summary>
			public static TzTimeZone St_Johns { get { return TzTimeInfo.GetZone("America/St_Johns"); } }
			/// <summary>
			/// Get the timezone for America/Swift_Current
			/// </summary>
			public static TzTimeZone Swift_Current { get { return TzTimeInfo.GetZone("America/Swift_Current"); } }
			/// <summary>
			/// Get the timezone for America/Tegucigalpa
			/// </summary>
			public static TzTimeZone Tegucigalpa { get { return TzTimeInfo.GetZone("America/Tegucigalpa"); } }
			/// <summary>
			/// Get the timezone for America/Thule
			/// </summary>
			public static TzTimeZone Thule { get { return TzTimeInfo.GetZone("America/Thule"); } }
			/// <summary>
			/// Get the timezone for America/Thunder_Bay
			/// </summary>
			public static TzTimeZone Thunder_Bay { get { return TzTimeInfo.GetZone("America/Thunder_Bay"); } }
			/// <summary>
			/// Get the timezone for America/Tijuana
			/// </summary>
			public static TzTimeZone Tijuana { get { return TzTimeInfo.GetZone("America/Tijuana"); } }
			/// <summary>
			/// Get the timezone for America/Toronto
			/// </summary>
			public static TzTimeZone Toronto { get { return TzTimeInfo.GetZone("America/Toronto"); } }
			/// <summary>
			/// Get the timezone for America/Vancouver
			/// </summary>
			public static TzTimeZone Vancouver { get { return TzTimeInfo.GetZone("America/Vancouver"); } }
			/// <summary>
			/// Get the timezone for America/Whitehorse
			/// </summary>
			public static TzTimeZone Whitehorse { get { return TzTimeInfo.GetZone("America/Whitehorse"); } }
			/// <summary>
			/// Get the timezone for America/Winnipeg
			/// </summary>
			public static TzTimeZone Winnipeg { get { return TzTimeInfo.GetZone("America/Winnipeg"); } }
			/// <summary>
			/// Get the timezone for America/Yakutat
			/// </summary>
			public static TzTimeZone Yakutat { get { return TzTimeInfo.GetZone("America/Yakutat"); } }
			/// <summary>
			/// Get the timezone for America/Yellowknife
			/// </summary>
			public static TzTimeZone Yellowknife { get { return TzTimeInfo.GetZone("America/Yellowknife"); } }
		}
		/// <summary>
		/// Represents all timezones for Antarctica
		/// </summary>
		public sealed class Antarctica {
			/// <summary>
			/// Initiliaze a new instance of <see cref="Antarctica"/>
			/// </summary>
			private Antarctica() { }

			/// <summary>
			/// Get the timezone for Antarctica/Casey
			/// </summary>
			public static TzTimeZone Casey { get { return TzTimeInfo.GetZone("Antarctica/Casey"); } }
			/// <summary>
			/// Get the timezone for Antarctica/Davis
			/// </summary>
			public static TzTimeZone Davis { get { return TzTimeInfo.GetZone("Antarctica/Davis"); } }
			/// <summary>
			/// Get the timezone for Antarctica/DumontDUrville
			/// </summary>
			public static TzTimeZone DumontDUrville { get { return TzTimeInfo.GetZone("Antarctica/DumontDUrville"); } }
			/// <summary>
			/// Get the timezone for Antarctica/Macquarie
			/// </summary>
			public static TzTimeZone Macquarie { get { return TzTimeInfo.GetZone("Antarctica/Macquarie"); } }
			/// <summary>
			/// Get the timezone for Antarctica/Mawson
			/// </summary>
			public static TzTimeZone Mawson { get { return TzTimeInfo.GetZone("Antarctica/Mawson"); } }
			/// <summary>
			/// Get the timezone for Antarctica/Palmer
			/// </summary>
			public static TzTimeZone Palmer { get { return TzTimeInfo.GetZone("Antarctica/Palmer"); } }
			/// <summary>
			/// Get the timezone for Antarctica/Rothera
			/// </summary>
			public static TzTimeZone Rothera { get { return TzTimeInfo.GetZone("Antarctica/Rothera"); } }
			/// <summary>
			/// Get the timezone for Antarctica/Syowa
			/// </summary>
			public static TzTimeZone Syowa { get { return TzTimeInfo.GetZone("Antarctica/Syowa"); } }
			/// <summary>
			/// Get the timezone for Antarctica/Troll
			/// </summary>
			public static TzTimeZone Troll { get { return TzTimeInfo.GetZone("Antarctica/Troll"); } }
			/// <summary>
			/// Get the timezone for Antarctica/Vostok
			/// </summary>
			public static TzTimeZone Vostok { get { return TzTimeInfo.GetZone("Antarctica/Vostok"); } }
		}
		/// <summary>
		/// Represents all timezones for Asia
		/// </summary>
		public sealed class Asia {
			/// <summary>
			/// Initiliaze a new instance of <see cref="Asia"/>
			/// </summary>
			private Asia() { }

			/// <summary>
			/// Get the timezone for Asia/Almaty
			/// </summary>
			public static TzTimeZone Almaty { get { return TzTimeInfo.GetZone("Asia/Almaty"); } }
			/// <summary>
			/// Get the timezone for Asia/Amman
			/// </summary>
			public static TzTimeZone Amman { get { return TzTimeInfo.GetZone("Asia/Amman"); } }
			/// <summary>
			/// Get the timezone for Asia/Anadyr
			/// </summary>
			public static TzTimeZone Anadyr { get { return TzTimeInfo.GetZone("Asia/Anadyr"); } }
			/// <summary>
			/// Get the timezone for Asia/Aqtau
			/// </summary>
			public static TzTimeZone Aqtau { get { return TzTimeInfo.GetZone("Asia/Aqtau"); } }
			/// <summary>
			/// Get the timezone for Asia/Aqtobe
			/// </summary>
			public static TzTimeZone Aqtobe { get { return TzTimeInfo.GetZone("Asia/Aqtobe"); } }
			/// <summary>
			/// Get the timezone for Asia/Ashgabat
			/// </summary>
			public static TzTimeZone Ashgabat { get { return TzTimeInfo.GetZone("Asia/Ashgabat"); } }
			/// <summary>
			/// Get the timezone for Asia/Baghdad
			/// </summary>
			public static TzTimeZone Baghdad { get { return TzTimeInfo.GetZone("Asia/Baghdad"); } }
			/// <summary>
			/// Get the timezone for Asia/Baku
			/// </summary>
			public static TzTimeZone Baku { get { return TzTimeInfo.GetZone("Asia/Baku"); } }
			/// <summary>
			/// Get the timezone for Asia/Bangkok
			/// </summary>
			public static TzTimeZone Bangkok { get { return TzTimeInfo.GetZone("Asia/Bangkok"); } }
			/// <summary>
			/// Get the timezone for Asia/Beirut
			/// </summary>
			public static TzTimeZone Beirut { get { return TzTimeInfo.GetZone("Asia/Beirut"); } }
			/// <summary>
			/// Get the timezone for Asia/Bishkek
			/// </summary>
			public static TzTimeZone Bishkek { get { return TzTimeInfo.GetZone("Asia/Bishkek"); } }
			/// <summary>
			/// Get the timezone for Asia/Brunei
			/// </summary>
			public static TzTimeZone Brunei { get { return TzTimeInfo.GetZone("Asia/Brunei"); } }
			/// <summary>
			/// Get the timezone for Asia/Chita
			/// </summary>
			public static TzTimeZone Chita { get { return TzTimeInfo.GetZone("Asia/Chita"); } }
			/// <summary>
			/// Get the timezone for Asia/Choibalsan
			/// </summary>
			public static TzTimeZone Choibalsan { get { return TzTimeInfo.GetZone("Asia/Choibalsan"); } }
			/// <summary>
			/// Get the timezone for Asia/Colombo
			/// </summary>
			public static TzTimeZone Colombo { get { return TzTimeInfo.GetZone("Asia/Colombo"); } }
			/// <summary>
			/// Get the timezone for Asia/Damascus
			/// </summary>
			public static TzTimeZone Damascus { get { return TzTimeInfo.GetZone("Asia/Damascus"); } }
			/// <summary>
			/// Get the timezone for Asia/Dhaka
			/// </summary>
			public static TzTimeZone Dhaka { get { return TzTimeInfo.GetZone("Asia/Dhaka"); } }
			/// <summary>
			/// Get the timezone for Asia/Dili
			/// </summary>
			public static TzTimeZone Dili { get { return TzTimeInfo.GetZone("Asia/Dili"); } }
			/// <summary>
			/// Get the timezone for Asia/Dubai
			/// </summary>
			public static TzTimeZone Dubai { get { return TzTimeInfo.GetZone("Asia/Dubai"); } }
			/// <summary>
			/// Get the timezone for Asia/Dushanbe
			/// </summary>
			public static TzTimeZone Dushanbe { get { return TzTimeInfo.GetZone("Asia/Dushanbe"); } }
			/// <summary>
			/// Get the timezone for Asia/Gaza
			/// </summary>
			public static TzTimeZone Gaza { get { return TzTimeInfo.GetZone("Asia/Gaza"); } }
			/// <summary>
			/// Get the timezone for Asia/Hebron
			/// </summary>
			public static TzTimeZone Hebron { get { return TzTimeInfo.GetZone("Asia/Hebron"); } }
			/// <summary>
			/// Get the timezone for Asia/Ho_Chi_Minh
			/// </summary>
			public static TzTimeZone Ho_Chi_Minh { get { return TzTimeInfo.GetZone("Asia/Ho_Chi_Minh"); } }
			/// <summary>
			/// Get the timezone for Asia/Hong_Kong
			/// </summary>
			public static TzTimeZone Hong_Kong { get { return TzTimeInfo.GetZone("Asia/Hong_Kong"); } }
			/// <summary>
			/// Get the timezone for Asia/Hovd
			/// </summary>
			public static TzTimeZone Hovd { get { return TzTimeInfo.GetZone("Asia/Hovd"); } }
			/// <summary>
			/// Get the timezone for Asia/Irkutsk
			/// </summary>
			public static TzTimeZone Irkutsk { get { return TzTimeInfo.GetZone("Asia/Irkutsk"); } }
			/// <summary>
			/// Get the timezone for Asia/Jakarta
			/// </summary>
			public static TzTimeZone Jakarta { get { return TzTimeInfo.GetZone("Asia/Jakarta"); } }
			/// <summary>
			/// Get the timezone for Asia/Jayapura
			/// </summary>
			public static TzTimeZone Jayapura { get { return TzTimeInfo.GetZone("Asia/Jayapura"); } }
			/// <summary>
			/// Get the timezone for Asia/Jerusalem
			/// </summary>
			public static TzTimeZone Jerusalem { get { return TzTimeInfo.GetZone("Asia/Jerusalem"); } }
			/// <summary>
			/// Get the timezone for Asia/Kabul
			/// </summary>
			public static TzTimeZone Kabul { get { return TzTimeInfo.GetZone("Asia/Kabul"); } }
			/// <summary>
			/// Get the timezone for Asia/Kamchatka
			/// </summary>
			public static TzTimeZone Kamchatka { get { return TzTimeInfo.GetZone("Asia/Kamchatka"); } }
			/// <summary>
			/// Get the timezone for Asia/Karachi
			/// </summary>
			public static TzTimeZone Karachi { get { return TzTimeInfo.GetZone("Asia/Karachi"); } }
			/// <summary>
			/// Get the timezone for Asia/Kathmandu
			/// </summary>
			public static TzTimeZone Kathmandu { get { return TzTimeInfo.GetZone("Asia/Kathmandu"); } }
			/// <summary>
			/// Get the timezone for Asia/Khandyga
			/// </summary>
			public static TzTimeZone Khandyga { get { return TzTimeInfo.GetZone("Asia/Khandyga"); } }
			/// <summary>
			/// Get the timezone for Asia/Kolkata
			/// </summary>
			public static TzTimeZone Kolkata { get { return TzTimeInfo.GetZone("Asia/Kolkata"); } }
			/// <summary>
			/// Get the timezone for Asia/Krasnoyarsk
			/// </summary>
			public static TzTimeZone Krasnoyarsk { get { return TzTimeInfo.GetZone("Asia/Krasnoyarsk"); } }
			/// <summary>
			/// Get the timezone for Asia/Kuala_Lumpur
			/// </summary>
			public static TzTimeZone Kuala_Lumpur { get { return TzTimeInfo.GetZone("Asia/Kuala_Lumpur"); } }
			/// <summary>
			/// Get the timezone for Asia/Kuching
			/// </summary>
			public static TzTimeZone Kuching { get { return TzTimeInfo.GetZone("Asia/Kuching"); } }
			/// <summary>
			/// Get the timezone for Asia/Macau
			/// </summary>
			public static TzTimeZone Macau { get { return TzTimeInfo.GetZone("Asia/Macau"); } }
			/// <summary>
			/// Get the timezone for Asia/Magadan
			/// </summary>
			public static TzTimeZone Magadan { get { return TzTimeInfo.GetZone("Asia/Magadan"); } }
			/// <summary>
			/// Get the timezone for Asia/Makassar
			/// </summary>
			public static TzTimeZone Makassar { get { return TzTimeInfo.GetZone("Asia/Makassar"); } }
			/// <summary>
			/// Get the timezone for Asia/Manila
			/// </summary>
			public static TzTimeZone Manila { get { return TzTimeInfo.GetZone("Asia/Manila"); } }
			/// <summary>
			/// Get the timezone for Asia/Nicosia
			/// </summary>
			public static TzTimeZone Nicosia { get { return TzTimeInfo.GetZone("Asia/Nicosia"); } }
			/// <summary>
			/// Get the timezone for Asia/Novokuznetsk
			/// </summary>
			public static TzTimeZone Novokuznetsk { get { return TzTimeInfo.GetZone("Asia/Novokuznetsk"); } }
			/// <summary>
			/// Get the timezone for Asia/Novosibirsk
			/// </summary>
			public static TzTimeZone Novosibirsk { get { return TzTimeInfo.GetZone("Asia/Novosibirsk"); } }
			/// <summary>
			/// Get the timezone for Asia/Omsk
			/// </summary>
			public static TzTimeZone Omsk { get { return TzTimeInfo.GetZone("Asia/Omsk"); } }
			/// <summary>
			/// Get the timezone for Asia/Oral
			/// </summary>
			public static TzTimeZone Oral { get { return TzTimeInfo.GetZone("Asia/Oral"); } }
			/// <summary>
			/// Get the timezone for Asia/Pontianak
			/// </summary>
			public static TzTimeZone Pontianak { get { return TzTimeInfo.GetZone("Asia/Pontianak"); } }
			/// <summary>
			/// Get the timezone for Asia/Pyongyang
			/// </summary>
			public static TzTimeZone Pyongyang { get { return TzTimeInfo.GetZone("Asia/Pyongyang"); } }
			/// <summary>
			/// Get the timezone for Asia/Qatar
			/// </summary>
			public static TzTimeZone Qatar { get { return TzTimeInfo.GetZone("Asia/Qatar"); } }
			/// <summary>
			/// Get the timezone for Asia/Qyzylorda
			/// </summary>
			public static TzTimeZone Qyzylorda { get { return TzTimeInfo.GetZone("Asia/Qyzylorda"); } }
			/// <summary>
			/// Get the timezone for Asia/Rangoon
			/// </summary>
			public static TzTimeZone Rangoon { get { return TzTimeInfo.GetZone("Asia/Rangoon"); } }
			/// <summary>
			/// Get the timezone for Asia/Riyadh
			/// </summary>
			public static TzTimeZone Riyadh { get { return TzTimeInfo.GetZone("Asia/Riyadh"); } }
			/// <summary>
			/// Get the timezone for Asia/Sakhalin
			/// </summary>
			public static TzTimeZone Sakhalin { get { return TzTimeInfo.GetZone("Asia/Sakhalin"); } }
			/// <summary>
			/// Get the timezone for Asia/Samarkand
			/// </summary>
			public static TzTimeZone Samarkand { get { return TzTimeInfo.GetZone("Asia/Samarkand"); } }
			/// <summary>
			/// Get the timezone for Asia/Seoul
			/// </summary>
			public static TzTimeZone Seoul { get { return TzTimeInfo.GetZone("Asia/Seoul"); } }
			/// <summary>
			/// Get the timezone for Asia/Shanghai
			/// </summary>
			public static TzTimeZone Shanghai { get { return TzTimeInfo.GetZone("Asia/Shanghai"); } }
			/// <summary>
			/// Get the timezone for Asia/Singapore
			/// </summary>
			public static TzTimeZone Singapore { get { return TzTimeInfo.GetZone("Asia/Singapore"); } }
			/// <summary>
			/// Get the timezone for Asia/Srednekolymsk
			/// </summary>
			public static TzTimeZone Srednekolymsk { get { return TzTimeInfo.GetZone("Asia/Srednekolymsk"); } }
			/// <summary>
			/// Get the timezone for Asia/Taipei
			/// </summary>
			public static TzTimeZone Taipei { get { return TzTimeInfo.GetZone("Asia/Taipei"); } }
			/// <summary>
			/// Get the timezone for Asia/Tashkent
			/// </summary>
			public static TzTimeZone Tashkent { get { return TzTimeInfo.GetZone("Asia/Tashkent"); } }
			/// <summary>
			/// Get the timezone for Asia/Tbilisi
			/// </summary>
			public static TzTimeZone Tbilisi { get { return TzTimeInfo.GetZone("Asia/Tbilisi"); } }
			/// <summary>
			/// Get the timezone for Asia/Tehran
			/// </summary>
			public static TzTimeZone Tehran { get { return TzTimeInfo.GetZone("Asia/Tehran"); } }
			/// <summary>
			/// Get the timezone for Asia/Thimphu
			/// </summary>
			public static TzTimeZone Thimphu { get { return TzTimeInfo.GetZone("Asia/Thimphu"); } }
			/// <summary>
			/// Get the timezone for Asia/Tokyo
			/// </summary>
			public static TzTimeZone Tokyo { get { return TzTimeInfo.GetZone("Asia/Tokyo"); } }
			/// <summary>
			/// Get the timezone for Asia/Ulaanbaatar
			/// </summary>
			public static TzTimeZone Ulaanbaatar { get { return TzTimeInfo.GetZone("Asia/Ulaanbaatar"); } }
			/// <summary>
			/// Get the timezone for Asia/Urumqi
			/// </summary>
			public static TzTimeZone Urumqi { get { return TzTimeInfo.GetZone("Asia/Urumqi"); } }
			/// <summary>
			/// Get the timezone for Asia/Ust-Nera
			/// </summary>
			public static TzTimeZone Ust_Nera { get { return TzTimeInfo.GetZone("Asia/Ust-Nera"); } }
			/// <summary>
			/// Get the timezone for Asia/Vladivostok
			/// </summary>
			public static TzTimeZone Vladivostok { get { return TzTimeInfo.GetZone("Asia/Vladivostok"); } }
			/// <summary>
			/// Get the timezone for Asia/Yakutsk
			/// </summary>
			public static TzTimeZone Yakutsk { get { return TzTimeInfo.GetZone("Asia/Yakutsk"); } }
			/// <summary>
			/// Get the timezone for Asia/Yekaterinburg
			/// </summary>
			public static TzTimeZone Yekaterinburg { get { return TzTimeInfo.GetZone("Asia/Yekaterinburg"); } }
			/// <summary>
			/// Get the timezone for Asia/Yerevan
			/// </summary>
			public static TzTimeZone Yerevan { get { return TzTimeInfo.GetZone("Asia/Yerevan"); } }
		}
		/// <summary>
		/// Represents all timezones for Atlantic
		/// </summary>
		public sealed class Atlantic {
			/// <summary>
			/// Initiliaze a new instance of <see cref="Atlantic"/>
			/// </summary>
			private Atlantic() { }

			/// <summary>
			/// Get the timezone for Atlantic/Azores
			/// </summary>
			public static TzTimeZone Azores { get { return TzTimeInfo.GetZone("Atlantic/Azores"); } }
			/// <summary>
			/// Get the timezone for Atlantic/Bermuda
			/// </summary>
			public static TzTimeZone Bermuda { get { return TzTimeInfo.GetZone("Atlantic/Bermuda"); } }
			/// <summary>
			/// Get the timezone for Atlantic/Canary
			/// </summary>
			public static TzTimeZone Canary { get { return TzTimeInfo.GetZone("Atlantic/Canary"); } }
			/// <summary>
			/// Get the timezone for Atlantic/Cape_Verde
			/// </summary>
			public static TzTimeZone Cape_Verde { get { return TzTimeInfo.GetZone("Atlantic/Cape_Verde"); } }
			/// <summary>
			/// Get the timezone for Atlantic/Faroe
			/// </summary>
			public static TzTimeZone Faroe { get { return TzTimeInfo.GetZone("Atlantic/Faroe"); } }
			/// <summary>
			/// Get the timezone for Atlantic/Madeira
			/// </summary>
			public static TzTimeZone Madeira { get { return TzTimeInfo.GetZone("Atlantic/Madeira"); } }
			/// <summary>
			/// Get the timezone for Atlantic/Reykjavik
			/// </summary>
			public static TzTimeZone Reykjavik { get { return TzTimeInfo.GetZone("Atlantic/Reykjavik"); } }
			/// <summary>
			/// Get the timezone for Atlantic/South_Georgia
			/// </summary>
			public static TzTimeZone South_Georgia { get { return TzTimeInfo.GetZone("Atlantic/South_Georgia"); } }
			/// <summary>
			/// Get the timezone for Atlantic/Stanley
			/// </summary>
			public static TzTimeZone Stanley { get { return TzTimeInfo.GetZone("Atlantic/Stanley"); } }
		}
		/// <summary>
		/// Represents all timezones for Australia
		/// </summary>
		public sealed class Australia {
			/// <summary>
			/// Initiliaze a new instance of <see cref="Australia"/>
			/// </summary>
			private Australia() { }

			/// <summary>
			/// Get the timezone for Australia/Adelaide
			/// </summary>
			public static TzTimeZone Adelaide { get { return TzTimeInfo.GetZone("Australia/Adelaide"); } }
			/// <summary>
			/// Get the timezone for Australia/Brisbane
			/// </summary>
			public static TzTimeZone Brisbane { get { return TzTimeInfo.GetZone("Australia/Brisbane"); } }
			/// <summary>
			/// Get the timezone for Australia/Broken_Hill
			/// </summary>
			public static TzTimeZone Broken_Hill { get { return TzTimeInfo.GetZone("Australia/Broken_Hill"); } }
			/// <summary>
			/// Get the timezone for Australia/Currie
			/// </summary>
			public static TzTimeZone Currie { get { return TzTimeInfo.GetZone("Australia/Currie"); } }
			/// <summary>
			/// Get the timezone for Australia/Darwin
			/// </summary>
			public static TzTimeZone Darwin { get { return TzTimeInfo.GetZone("Australia/Darwin"); } }
			/// <summary>
			/// Get the timezone for Australia/Eucla
			/// </summary>
			public static TzTimeZone Eucla { get { return TzTimeInfo.GetZone("Australia/Eucla"); } }
			/// <summary>
			/// Get the timezone for Australia/Hobart
			/// </summary>
			public static TzTimeZone Hobart { get { return TzTimeInfo.GetZone("Australia/Hobart"); } }
			/// <summary>
			/// Get the timezone for Australia/Lindeman
			/// </summary>
			public static TzTimeZone Lindeman { get { return TzTimeInfo.GetZone("Australia/Lindeman"); } }
			/// <summary>
			/// Get the timezone for Australia/Lord_Howe
			/// </summary>
			public static TzTimeZone Lord_Howe { get { return TzTimeInfo.GetZone("Australia/Lord_Howe"); } }
			/// <summary>
			/// Get the timezone for Australia/Melbourne
			/// </summary>
			public static TzTimeZone Melbourne { get { return TzTimeInfo.GetZone("Australia/Melbourne"); } }
			/// <summary>
			/// Get the timezone for Australia/Perth
			/// </summary>
			public static TzTimeZone Perth { get { return TzTimeInfo.GetZone("Australia/Perth"); } }
			/// <summary>
			/// Get the timezone for Australia/Sydney
			/// </summary>
			public static TzTimeZone Sydney { get { return TzTimeInfo.GetZone("Australia/Sydney"); } }
		}
		/// <summary>
		/// Represents all timezones for Europe
		/// </summary>
		public sealed class Europe {
			/// <summary>
			/// Initiliaze a new instance of <see cref="Europe"/>
			/// </summary>
			private Europe() { }

			/// <summary>
			/// Get the timezone for Europe/Amsterdam
			/// </summary>
			public static TzTimeZone Amsterdam { get { return TzTimeInfo.GetZone("Europe/Amsterdam"); } }
			/// <summary>
			/// Get the timezone for Europe/Andorra
			/// </summary>
			public static TzTimeZone Andorra { get { return TzTimeInfo.GetZone("Europe/Andorra"); } }
			/// <summary>
			/// Get the timezone for Europe/Athens
			/// </summary>
			public static TzTimeZone Athens { get { return TzTimeInfo.GetZone("Europe/Athens"); } }
			/// <summary>
			/// Get the timezone for Europe/Belgrade
			/// </summary>
			public static TzTimeZone Belgrade { get { return TzTimeInfo.GetZone("Europe/Belgrade"); } }
			/// <summary>
			/// Get the timezone for Europe/Berlin
			/// </summary>
			public static TzTimeZone Berlin { get { return TzTimeInfo.GetZone("Europe/Berlin"); } }
			/// <summary>
			/// Get the timezone for Europe/Brussels
			/// </summary>
			public static TzTimeZone Brussels { get { return TzTimeInfo.GetZone("Europe/Brussels"); } }
			/// <summary>
			/// Get the timezone for Europe/Bucharest
			/// </summary>
			public static TzTimeZone Bucharest { get { return TzTimeInfo.GetZone("Europe/Bucharest"); } }
			/// <summary>
			/// Get the timezone for Europe/Budapest
			/// </summary>
			public static TzTimeZone Budapest { get { return TzTimeInfo.GetZone("Europe/Budapest"); } }
			/// <summary>
			/// Get the timezone for Europe/Chisinau
			/// </summary>
			public static TzTimeZone Chisinau { get { return TzTimeInfo.GetZone("Europe/Chisinau"); } }
			/// <summary>
			/// Get the timezone for Europe/Copenhagen
			/// </summary>
			public static TzTimeZone Copenhagen { get { return TzTimeInfo.GetZone("Europe/Copenhagen"); } }
			/// <summary>
			/// Get the timezone for Europe/Dublin
			/// </summary>
			public static TzTimeZone Dublin { get { return TzTimeInfo.GetZone("Europe/Dublin"); } }
			/// <summary>
			/// Get the timezone for Europe/Gibraltar
			/// </summary>
			public static TzTimeZone Gibraltar { get { return TzTimeInfo.GetZone("Europe/Gibraltar"); } }
			/// <summary>
			/// Get the timezone for Europe/Helsinki
			/// </summary>
			public static TzTimeZone Helsinki { get { return TzTimeInfo.GetZone("Europe/Helsinki"); } }
			/// <summary>
			/// Get the timezone for Europe/Istanbul
			/// </summary>
			public static TzTimeZone Istanbul { get { return TzTimeInfo.GetZone("Europe/Istanbul"); } }
			/// <summary>
			/// Get the timezone for Europe/Kaliningrad
			/// </summary>
			public static TzTimeZone Kaliningrad { get { return TzTimeInfo.GetZone("Europe/Kaliningrad"); } }
			/// <summary>
			/// Get the timezone for Europe/Kiev
			/// </summary>
			public static TzTimeZone Kiev { get { return TzTimeInfo.GetZone("Europe/Kiev"); } }
			/// <summary>
			/// Get the timezone for Europe/Lisbon
			/// </summary>
			public static TzTimeZone Lisbon { get { return TzTimeInfo.GetZone("Europe/Lisbon"); } }
			/// <summary>
			/// Get the timezone for Europe/London
			/// </summary>
			public static TzTimeZone London { get { return TzTimeInfo.GetZone("Europe/London"); } }
			/// <summary>
			/// Get the timezone for Europe/Luxembourg
			/// </summary>
			public static TzTimeZone Luxembourg { get { return TzTimeInfo.GetZone("Europe/Luxembourg"); } }
			/// <summary>
			/// Get the timezone for Europe/Madrid
			/// </summary>
			public static TzTimeZone Madrid { get { return TzTimeInfo.GetZone("Europe/Madrid"); } }
			/// <summary>
			/// Get the timezone for Europe/Malta
			/// </summary>
			public static TzTimeZone Malta { get { return TzTimeInfo.GetZone("Europe/Malta"); } }
			/// <summary>
			/// Get the timezone for Europe/Minsk
			/// </summary>
			public static TzTimeZone Minsk { get { return TzTimeInfo.GetZone("Europe/Minsk"); } }
			/// <summary>
			/// Get the timezone for Europe/Monaco
			/// </summary>
			public static TzTimeZone Monaco { get { return TzTimeInfo.GetZone("Europe/Monaco"); } }
			/// <summary>
			/// Get the timezone for Europe/Moscow
			/// </summary>
			public static TzTimeZone Moscow { get { return TzTimeInfo.GetZone("Europe/Moscow"); } }
			/// <summary>
			/// Get the timezone for Europe/Oslo
			/// </summary>
			public static TzTimeZone Oslo { get { return TzTimeInfo.GetZone("Europe/Oslo"); } }
			/// <summary>
			/// Get the timezone for Europe/Paris
			/// </summary>
			public static TzTimeZone Paris { get { return TzTimeInfo.GetZone("Europe/Paris"); } }
			/// <summary>
			/// Get the timezone for Europe/Prague
			/// </summary>
			public static TzTimeZone Prague { get { return TzTimeInfo.GetZone("Europe/Prague"); } }
			/// <summary>
			/// Get the timezone for Europe/Riga
			/// </summary>
			public static TzTimeZone Riga { get { return TzTimeInfo.GetZone("Europe/Riga"); } }
			/// <summary>
			/// Get the timezone for Europe/Rome
			/// </summary>
			public static TzTimeZone Rome { get { return TzTimeInfo.GetZone("Europe/Rome"); } }
			/// <summary>
			/// Get the timezone for Europe/Samara
			/// </summary>
			public static TzTimeZone Samara { get { return TzTimeInfo.GetZone("Europe/Samara"); } }
			/// <summary>
			/// Get the timezone for Europe/Simferopol
			/// </summary>
			public static TzTimeZone Simferopol { get { return TzTimeInfo.GetZone("Europe/Simferopol"); } }
			/// <summary>
			/// Get the timezone for Europe/Sofia
			/// </summary>
			public static TzTimeZone Sofia { get { return TzTimeInfo.GetZone("Europe/Sofia"); } }
			/// <summary>
			/// Get the timezone for Europe/Stockholm
			/// </summary>
			public static TzTimeZone Stockholm { get { return TzTimeInfo.GetZone("Europe/Stockholm"); } }
			/// <summary>
			/// Get the timezone for Europe/Tallinn
			/// </summary>
			public static TzTimeZone Tallinn { get { return TzTimeInfo.GetZone("Europe/Tallinn"); } }
			/// <summary>
			/// Get the timezone for Europe/Tirane
			/// </summary>
			public static TzTimeZone Tirane { get { return TzTimeInfo.GetZone("Europe/Tirane"); } }
			/// <summary>
			/// Get the timezone for Europe/Uzhgorod
			/// </summary>
			public static TzTimeZone Uzhgorod { get { return TzTimeInfo.GetZone("Europe/Uzhgorod"); } }
			/// <summary>
			/// Get the timezone for Europe/Vienna
			/// </summary>
			public static TzTimeZone Vienna { get { return TzTimeInfo.GetZone("Europe/Vienna"); } }
			/// <summary>
			/// Get the timezone for Europe/Vilnius
			/// </summary>
			public static TzTimeZone Vilnius { get { return TzTimeInfo.GetZone("Europe/Vilnius"); } }
			/// <summary>
			/// Get the timezone for Europe/Volgograd
			/// </summary>
			public static TzTimeZone Volgograd { get { return TzTimeInfo.GetZone("Europe/Volgograd"); } }
			/// <summary>
			/// Get the timezone for Europe/Warsaw
			/// </summary>
			public static TzTimeZone Warsaw { get { return TzTimeInfo.GetZone("Europe/Warsaw"); } }
			/// <summary>
			/// Get the timezone for Europe/Zaporozhye
			/// </summary>
			public static TzTimeZone Zaporozhye { get { return TzTimeInfo.GetZone("Europe/Zaporozhye"); } }
			/// <summary>
			/// Get the timezone for Europe/Zurich
			/// </summary>
			public static TzTimeZone Zurich { get { return TzTimeInfo.GetZone("Europe/Zurich"); } }
		}
		/// <summary>
		/// Represents all timezones for Indian
		/// </summary>
		public sealed class Indian {
			/// <summary>
			/// Initiliaze a new instance of <see cref="Indian"/>
			/// </summary>
			private Indian() { }

			/// <summary>
			/// Get the timezone for Indian/Chagos
			/// </summary>
			public static TzTimeZone Chagos { get { return TzTimeInfo.GetZone("Indian/Chagos"); } }
			/// <summary>
			/// Get the timezone for Indian/Christmas
			/// </summary>
			public static TzTimeZone Christmas { get { return TzTimeInfo.GetZone("Indian/Christmas"); } }
			/// <summary>
			/// Get the timezone for Indian/Cocos
			/// </summary>
			public static TzTimeZone Cocos { get { return TzTimeInfo.GetZone("Indian/Cocos"); } }
			/// <summary>
			/// Get the timezone for Indian/Kerguelen
			/// </summary>
			public static TzTimeZone Kerguelen { get { return TzTimeInfo.GetZone("Indian/Kerguelen"); } }
			/// <summary>
			/// Get the timezone for Indian/Mahe
			/// </summary>
			public static TzTimeZone Mahe { get { return TzTimeInfo.GetZone("Indian/Mahe"); } }
			/// <summary>
			/// Get the timezone for Indian/Maldives
			/// </summary>
			public static TzTimeZone Maldives { get { return TzTimeInfo.GetZone("Indian/Maldives"); } }
			/// <summary>
			/// Get the timezone for Indian/Mauritius
			/// </summary>
			public static TzTimeZone Mauritius { get { return TzTimeInfo.GetZone("Indian/Mauritius"); } }
			/// <summary>
			/// Get the timezone for Indian/Reunion
			/// </summary>
			public static TzTimeZone Reunion { get { return TzTimeInfo.GetZone("Indian/Reunion"); } }
		}
		/// <summary>
		/// Represents all timezones for Pacific
		/// </summary>
		public sealed class Pacific {
			/// <summary>
			/// Initiliaze a new instance of <see cref="Pacific"/>
			/// </summary>
			private Pacific() { }

			/// <summary>
			/// Get the timezone for Pacific/Apia
			/// </summary>
			public static TzTimeZone Apia { get { return TzTimeInfo.GetZone("Pacific/Apia"); } }
			/// <summary>
			/// Get the timezone for Pacific/Auckland
			/// </summary>
			public static TzTimeZone Auckland { get { return TzTimeInfo.GetZone("Pacific/Auckland"); } }
			/// <summary>
			/// Get the timezone for Pacific/Bougainville
			/// </summary>
			public static TzTimeZone Bougainville { get { return TzTimeInfo.GetZone("Pacific/Bougainville"); } }
			/// <summary>
			/// Get the timezone for Pacific/Chatham
			/// </summary>
			public static TzTimeZone Chatham { get { return TzTimeInfo.GetZone("Pacific/Chatham"); } }
			/// <summary>
			/// Get the timezone for Pacific/Chuuk
			/// </summary>
			public static TzTimeZone Chuuk { get { return TzTimeInfo.GetZone("Pacific/Chuuk"); } }
			/// <summary>
			/// Get the timezone for Pacific/Easter
			/// </summary>
			public static TzTimeZone Easter { get { return TzTimeInfo.GetZone("Pacific/Easter"); } }
			/// <summary>
			/// Get the timezone for Pacific/Efate
			/// </summary>
			public static TzTimeZone Efate { get { return TzTimeInfo.GetZone("Pacific/Efate"); } }
			/// <summary>
			/// Get the timezone for Pacific/Enderbury
			/// </summary>
			public static TzTimeZone Enderbury { get { return TzTimeInfo.GetZone("Pacific/Enderbury"); } }
			/// <summary>
			/// Get the timezone for Pacific/Fakaofo
			/// </summary>
			public static TzTimeZone Fakaofo { get { return TzTimeInfo.GetZone("Pacific/Fakaofo"); } }
			/// <summary>
			/// Get the timezone for Pacific/Fiji
			/// </summary>
			public static TzTimeZone Fiji { get { return TzTimeInfo.GetZone("Pacific/Fiji"); } }
			/// <summary>
			/// Get the timezone for Pacific/Funafuti
			/// </summary>
			public static TzTimeZone Funafuti { get { return TzTimeInfo.GetZone("Pacific/Funafuti"); } }
			/// <summary>
			/// Get the timezone for Pacific/Galapagos
			/// </summary>
			public static TzTimeZone Galapagos { get { return TzTimeInfo.GetZone("Pacific/Galapagos"); } }
			/// <summary>
			/// Get the timezone for Pacific/Gambier
			/// </summary>
			public static TzTimeZone Gambier { get { return TzTimeInfo.GetZone("Pacific/Gambier"); } }
			/// <summary>
			/// Get the timezone for Pacific/Guadalcanal
			/// </summary>
			public static TzTimeZone Guadalcanal { get { return TzTimeInfo.GetZone("Pacific/Guadalcanal"); } }
			/// <summary>
			/// Get the timezone for Pacific/Guam
			/// </summary>
			public static TzTimeZone Guam { get { return TzTimeInfo.GetZone("Pacific/Guam"); } }
			/// <summary>
			/// Get the timezone for Pacific/Honolulu
			/// </summary>
			public static TzTimeZone Honolulu { get { return TzTimeInfo.GetZone("Pacific/Honolulu"); } }
			/// <summary>
			/// Get the timezone for Pacific/Kiritimati
			/// </summary>
			public static TzTimeZone Kiritimati { get { return TzTimeInfo.GetZone("Pacific/Kiritimati"); } }
			/// <summary>
			/// Get the timezone for Pacific/Kosrae
			/// </summary>
			public static TzTimeZone Kosrae { get { return TzTimeInfo.GetZone("Pacific/Kosrae"); } }
			/// <summary>
			/// Get the timezone for Pacific/Kwajalein
			/// </summary>
			public static TzTimeZone Kwajalein { get { return TzTimeInfo.GetZone("Pacific/Kwajalein"); } }
			/// <summary>
			/// Get the timezone for Pacific/Majuro
			/// </summary>
			public static TzTimeZone Majuro { get { return TzTimeInfo.GetZone("Pacific/Majuro"); } }
			/// <summary>
			/// Get the timezone for Pacific/Marquesas
			/// </summary>
			public static TzTimeZone Marquesas { get { return TzTimeInfo.GetZone("Pacific/Marquesas"); } }
			/// <summary>
			/// Get the timezone for Pacific/Nauru
			/// </summary>
			public static TzTimeZone Nauru { get { return TzTimeInfo.GetZone("Pacific/Nauru"); } }
			/// <summary>
			/// Get the timezone for Pacific/Niue
			/// </summary>
			public static TzTimeZone Niue { get { return TzTimeInfo.GetZone("Pacific/Niue"); } }
			/// <summary>
			/// Get the timezone for Pacific/Norfolk
			/// </summary>
			public static TzTimeZone Norfolk { get { return TzTimeInfo.GetZone("Pacific/Norfolk"); } }
			/// <summary>
			/// Get the timezone for Pacific/Noumea
			/// </summary>
			public static TzTimeZone Noumea { get { return TzTimeInfo.GetZone("Pacific/Noumea"); } }
			/// <summary>
			/// Get the timezone for Pacific/Pago_Pago
			/// </summary>
			public static TzTimeZone Pago_Pago { get { return TzTimeInfo.GetZone("Pacific/Pago_Pago"); } }
			/// <summary>
			/// Get the timezone for Pacific/Palau
			/// </summary>
			public static TzTimeZone Palau { get { return TzTimeInfo.GetZone("Pacific/Palau"); } }
			/// <summary>
			/// Get the timezone for Pacific/Pitcairn
			/// </summary>
			public static TzTimeZone Pitcairn { get { return TzTimeInfo.GetZone("Pacific/Pitcairn"); } }
			/// <summary>
			/// Get the timezone for Pacific/Pohnpei
			/// </summary>
			public static TzTimeZone Pohnpei { get { return TzTimeInfo.GetZone("Pacific/Pohnpei"); } }
			/// <summary>
			/// Get the timezone for Pacific/Port_Moresby
			/// </summary>
			public static TzTimeZone Port_Moresby { get { return TzTimeInfo.GetZone("Pacific/Port_Moresby"); } }
			/// <summary>
			/// Get the timezone for Pacific/Rarotonga
			/// </summary>
			public static TzTimeZone Rarotonga { get { return TzTimeInfo.GetZone("Pacific/Rarotonga"); } }
			/// <summary>
			/// Get the timezone for Pacific/Tahiti
			/// </summary>
			public static TzTimeZone Tahiti { get { return TzTimeInfo.GetZone("Pacific/Tahiti"); } }
			/// <summary>
			/// Get the timezone for Pacific/Tarawa
			/// </summary>
			public static TzTimeZone Tarawa { get { return TzTimeInfo.GetZone("Pacific/Tarawa"); } }
			/// <summary>
			/// Get the timezone for Pacific/Tongatapu
			/// </summary>
			public static TzTimeZone Tongatapu { get { return TzTimeInfo.GetZone("Pacific/Tongatapu"); } }
			/// <summary>
			/// Get the timezone for Pacific/Wake
			/// </summary>
			public static TzTimeZone Wake { get { return TzTimeInfo.GetZone("Pacific/Wake"); } }
			/// <summary>
			/// Get the timezone for Pacific/Wallis
			/// </summary>
			public static TzTimeZone Wallis { get { return TzTimeInfo.GetZone("Pacific/Wallis"); } }
		}
	}
}

